-- Enable the extensions required for the agreed PostgreSQL foundation.
-- citext provides case-insensitive text comparison for email addresses.
-- UUIDs are generated by the Go application and stored as UUID values.

CREATE EXTENSION IF NOT EXISTS citext;
